source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml', "~> 4.0"
# gem 'geocollider', :path => '/Users/ryan/source/dc3/geocollider'
gem 'geocollider', :git => 'https://github.com/isawnyu/geocollider.git'
gem 'rack-attack'
gem 'activesupport', '>= 3.0.0'
gem 'airbrake'
gem 'rest-client'
gem 'sucker_punch'
gem 'rack-test'
gem 'rake'
gem 'minitest'

# JS/CSS assset management
gem 'sprockets'
gem 'uglifier'
gem 'sass'
gem 'coffee-script'
gem 'execjs'
