source 'https://rubygems.org'
gem 'sinatra'
gem 'haml'
gem 'geocollider', :path => '/Users/ryan/source/dc3/geocollider'
# gem 'geocollider', :git => 'https://github.com/ryanfb/geocollider.git'
gem 'rack-attack'
gem 'activesupport', '>= 3.0.0'
gem 'airbrake'
gem 'rest-client'
gem 'sucker_punch'

# JS/CSS assset management
gem 'sprockets'
gem 'uglifier'
gem 'sass'
gem 'coffee-script'
gem 'execjs'
